-- CreateTable
CREATE TABLE "Sala9a11" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "idade" INTEGER NOT NULL,
    "pontos" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "Sala6a8" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "idade" INTEGER NOT NULL,
    "pontos" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "Sala3a5" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "idade" INTEGER NOT NULL,
    "pontos" INTEGER NOT NULL
);
